name = "SpinDynamics"
uuid = "4b2ecb80-f16d-4f8a-8c73-18108c4ee9c0"
authors = ["Matteo Boselli"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
